#Eazzy Server Utils Configuration
#maxHomes: Maximum number of homes per player
#homeCooldown: Cooldown in seconds for home commands
#maxWarps: Maximum number of global warps
#warpCooldown: Cooldown in seconds for warp commands
#tpaCooldown: Cooldown in seconds for TPA requests
#tpaTimeout: Time in seconds before a TPA request expires
#headCooldown: Cooldown in seconds for the head command
#Sat Jul 04 12:26:57 CEST 2026
headCooldown=3600
homeCooldown=5
maxHomes=8
maxWarps=100
tpaCooldown=3
tpaTimeout=12
warpCooldown=5
