# General Properties
java_version=17
minecraft_version=1.20.1
compatible_mc_versions=["1.20.1"]

# Forge-specific Properties
forge_loader=47.4.10

# NeoForge-specific Properties (unused for 1.20.1, required by build script)
neoforge_loader=0.0.0

# Fabric-specific Properties (used by common project for mixin support)
fabric_loader=0.15.11

# Selected loaders
builds_for=forge
